package archive

import (
	"archive/zip"
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/turbra/scrubctl/internal/sanitize"
	"github.com/turbra/scrubctl/internal/types"
)

type ScanArchiveSummary struct {
	ArchiveName   string `json:"archiveName"`
	ManifestCount int    `json:"manifestCount"`
	WarningCount  int    `json:"warningCount"`
}

func CountExportableResources(scan types.NamespaceScan) int {
	return len(getExportableResources(scan))
}

func CountWarningResources(scan types.NamespaceScan) int {
	count := 0
	for _, resource := range scan.Status.ResourceDetails {
		if resource.Classification == types.ClassificationCleanup || resource.Classification == types.ClassificationReview {
			count++
		}
	}
	return count
}

func BuildScanArchive(scan types.NamespaceScan) ([]byte, ScanArchiveSummary, error) {
	exportableResources := getExportableResources(scan)
	if len(exportableResources) == 0 {
		return nil, ScanArchiveSummary{}, ErrNoExportableResources
	}

	archiveName := buildArchiveName(scan)
	var buf bytes.Buffer
	zipWriter := zip.NewWriter(&buf)
	manifestPaths := map[string]struct{}{}

	if err := writeFile(zipWriter, "README.md", buildReadme(scan, exportableResources)); err != nil {
		return nil, ScanArchiveSummary{}, err
	}
	if warnings := buildWarnings(scan, exportableResources); warnings != "" {
		if err := writeFile(zipWriter, "WARNINGS.md", warnings); err != nil {
			return nil, ScanArchiveSummary{}, err
		}
	}
	for _, resource := range exportableResources {
		path := buildManifestPath(resource, manifestPaths)
		if err := writeFile(zipWriter, path, sanitize.SerializeResource(resource.SanitizedResource)); err != nil {
			return nil, ScanArchiveSummary{}, err
		}
	}
	if err := zipWriter.Close(); err != nil {
		return nil, ScanArchiveSummary{}, err
	}

	return buf.Bytes(), ScanArchiveSummary{
		ArchiveName:   archiveName,
		ManifestCount: len(exportableResources),
		WarningCount:  CountWarningResources(scan),
	}, nil
}

func WriteScanArchive(scan types.NamespaceScan, outDir string) (string, ScanArchiveSummary, error) {
	contents, summary, err := BuildScanArchive(scan)
	if err != nil {
		return "", ScanArchiveSummary{}, err
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", ScanArchiveSummary{}, err
	}
	fullPath := filepath.Join(outDir, summary.ArchiveName)
	if err := os.WriteFile(fullPath, contents, 0o644); err != nil {
		return "", ScanArchiveSummary{}, err
	}
	return fullPath, summary, nil
}

type exportableResource struct {
	types.ResourceClassification
}

var ErrNoExportableResources = errors.New("No exportable resources are available for this scan")

func getExportableResources(scan types.NamespaceScan) []exportableResource {
	exportable := make([]exportableResource, 0, len(scan.Status.ResourceDetails))
	for _, resource := range scan.Status.ResourceDetails {
		if resource.Classification == types.ClassificationExclude || resource.SanitizedResource == nil {
			continue
		}
		exportable = append(exportable, exportableResource{ResourceClassification: resource})
	}
	return exportable
}

func buildArchiveName(scan types.NamespaceScan) string {
	return "gitops-export-" + sanitizeSegment(scan.Metadata.Namespace) + "-" + formatTimestamp(scan.Metadata.ScannedAt) + ".zip"
}

func buildManifestPath(resource exportableResource, manifestPaths map[string]struct{}) string {
	baseName := toKebabCase(resource.Kind) + "-" + sanitizeSegment(resource.Name) + ".yaml"
	path := "manifests/" + string(resource.Classification) + "/" + baseName
	duplicate := 2
	for {
		if _, exists := manifestPaths[path]; !exists {
			manifestPaths[path] = struct{}{}
			return path
		}
		path = "manifests/" + string(resource.Classification) + "/" + strings.TrimSuffix(baseName, ".yaml") + "-" + itoa(duplicate) + ".yaml"
		duplicate++
	}
}

func buildReadme(scan types.NamespaceScan, resources []exportableResource) string {
	lines := []string{
		"# GitOps Export archive",
		"",
		"Namespace: " + scan.Spec.Namespace,
		"Scanned at: " + scan.Metadata.ScannedAt,
		"Secret handling: " + defaultString(scan.Spec.SecretHandling, "redact"),
		"",
		"Archive layout:",
		"- manifests/include/: resources classified as include",
		"- manifests/cleanup/: resources classified as cleanup",
		"- manifests/review/: resources classified as review",
		"",
		"Classification handling:",
		"- include resources are exported directly",
		"- cleanup resources are exported and also listed in WARNINGS.md",
		"- review resources are exported and also listed in WARNINGS.md",
		"- exclude resources are not exported",
		"",
		"Manifest files written: " + itoa(len(resources)),
		"",
		"This archive was generated by GitOps Export.",
	}
	return strings.Join(lines, "\n")
}

func buildWarnings(scan types.NamespaceScan, resources []exportableResource) string {
	var cleanupResources, reviewResources []exportableResource
	for _, resource := range resources {
		switch resource.Classification {
		case types.ClassificationCleanup:
			cleanupResources = append(cleanupResources, resource)
		case types.ClassificationReview:
			reviewResources = append(reviewResources, resource)
		}
	}
	var skipped []types.ResourceClassification
	for _, resource := range scan.Status.ResourceDetails {
		if resource.Classification == types.ClassificationExclude || resource.SanitizedResource == nil {
			skipped = append(skipped, resource)
		}
	}

	if len(cleanupResources) == 0 && len(reviewResources) == 0 && len(skipped) == 0 {
		return ""
	}

	lines := []string{"# Export warnings", ""}
	if len(cleanupResources) > 0 {
		lines = append(lines, "Cleanup resources included in the archive:")
		for _, resource := range cleanupResources {
			lines = append(lines, "- "+resource.Kind+"/"+resource.Name+": "+resource.Reason)
		}
		lines = append(lines, "")
	}
	if len(reviewResources) > 0 {
		lines = append(lines, "Review resources included in the archive:")
		for _, resource := range reviewResources {
			lines = append(lines, "- "+resource.Kind+"/"+resource.Name+": "+resource.Reason)
		}
		lines = append(lines, "")
	}
	if len(skipped) > 0 {
		lines = append(lines, "Resources not written to the archive:")
		for _, resource := range skipped {
			reason := resource.Reason
			if resource.SanitizedResource == nil && resource.Kind == "Secret" {
				reason = "Secret omitted by current secret handling"
			}
			lines = append(lines, "- "+resource.Kind+"/"+resource.Name+": "+reason)
		}
	}

	return strings.TrimRight(strings.Join(lines, "\n"), "\n")
}

func writeFile(z *zip.Writer, path, content string) error {
	writer, err := z.Create(path)
	if err != nil {
		return err
	}
	_, err = writer.Write([]byte(content))
	return err
}

func formatTimestamp(value string) string {
	value = strings.ReplaceAll(value, "-", "")
	value = strings.ReplaceAll(value, ":", "")
	if idx := strings.Index(value, "."); idx >= 0 && strings.HasSuffix(value, "Z") {
		return value[:idx] + "Z"
	}
	return value
}

func sanitizeSegment(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	var builder strings.Builder
	lastDash := false
	for _, r := range value {
		isAllowed := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '.' || r == '_' || r == '-'
		if isAllowed {
			builder.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash {
			builder.WriteByte('-')
			lastDash = true
		}
	}
	result := strings.Trim(builder.String(), "-")
	if result == "" {
		return "resource"
	}
	return result
}

func toKebabCase(value string) string {
	var builder strings.Builder
	for i, r := range value {
		if i > 0 && r >= 'A' && r <= 'Z' {
			prev := rune(value[i-1])
			if (prev >= 'a' && prev <= 'z') || (prev >= '0' && prev <= '9') {
				builder.WriteByte('-')
			}
		}
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			builder.WriteRune(toLower(r))
		} else {
			builder.WriteByte('-')
		}
	}
	return strings.Trim(builder.String(), "-")
}

func toLower(r rune) rune {
	if r >= 'A' && r <= 'Z' {
		return r + ('a' - 'A')
	}
	return r
}

func defaultString(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func itoa(value int) string {
	return strconv.Itoa(value)
}
